@hostAddress = https://app-gamestore-be-dev-southeastasia-01.azurewebsites.net/

GET {{hostAddress}}/games



###
GET {{hostAddress}}/games/3

###
POST {{hostAddress}}/games
Content-Type: application/json

{
    "name": "Morning fighter 1",
    "genreId":3,
    "price": 39.99,
    "releaseDate": "2001-11-18"
}

###
PUT  {{hostAddress}}/games/3  
Content-Type: application/json

  {
    "name": "api raja ibbo",
    "genreId": 2,
    "price": 9.99,
    "releaseDate": "2017-03-03"
  }

###
DELETE {{hostAddress}}/games/2

