GET http://localhost:5001/games

###
GET http://localhost:5001/games/3

###
POST  http://localhost:5001/games
Content-Type: application/json

{
    "name": "Morning fighter 1",
    "genreId":3,
    "price": 39.99,
    "releaseDate": "2001-11-18"
}

###
PUT  http://localhost:5001/games/3  
Content-Type: application/json

  {
    "name": "api raja ibbo",
    "genreId": 2,
    "price": 9.99,
    "releaseDate": "2017-03-03"
  }

###
DELETE http://localhost:5001/games/2

